### ISSUE TITLE
Fix readme to reference macro_rules_derive

### ISSUE THREAD

**Issue by douglas-raillard-arm** [danielhenrymantilla/macro_rules_attribute-rs#13]
README.md currently contains this snippet:
```rust
macro_rules! MyFancyDerive { /* … */ }

#[derive(MyFancyDerive!)]
struct Foo { /* … */ }
```

This will not compile. From my understanding of this code https://github.com/danielhenrymantilla/macro_rules_attribute-rs/blob/f7514b6752066a1fbac272c5a657190965915f7d/src/lib.rs#L224 it should contain this instead:
```rust
#[macro_rules_derive(MyFancyDerive!)]
```

**Comment by danielhenrymantilla** [comment]
That example was indeed missing an explanation; a fix for that was submitted a few days ago (issue: #11, pr: #12), and it has just been merged:

https://github.com/danielhenrymantilla/macro_rules_attribute-rs/blob/181640ca57c78fa49f1950ccd9222387d1699568/README.md#L15

The idea is that you need to use the `#[derive]` of this crate rather than the built-in one, precisely to support "banged `Derive!`s"

**Comment by douglas-raillard-arm** [comment]
Ah ok makes sense, I did not realize the crate overrides the `derive()` attribute itself. I did not even know it was possible to do so, Rust is really quite flexible.
