### ISSUE TITLE
Automatically adding the `!` instead of letting the user type it out

### ISSUE THREAD

**Issue by 90-008** [danielhenrymantilla/macro_rules_attribute-rs#3]
This is kind of a nitpick-y request, but I'd like it if it could also take for example `crate::some_macro` instead of `crate::some_macro!`. The way I see it this attribute feels like it should just take a path to a macro, plus I think it looks better that way. I can make a PR if it is welcome.

**Comment by danielhenrymantilla** [comment]
Yeah, fair enough, I don't have strong opinions here, so either is fine by me. I guess I could make it _optional_, so as to keep retro-compatibility, and let the callers that desire so skip it 🙂

I appreciate the PR suggestion, although, I'd like to get rid of that lazy stuff I put there, whereby I don't validate that the given stuff is indeed a macro path (that is, since we don't use `syn`, we'd need to parse an alternate sequence of `Punct(':', Spacing::Joint), Punct(':', Spacing::Alone), Ident` (with an optional leading `::`));

**Comment by 90-008** [comment]
> Yeah, fair enough, I don't have strong opinions here, so either is fine by me. I guess I could make it _optional_, so as to keep retro-compatibility, and let the callers that desire so skip it

Yes, I think we can make it optional so that if a `!` is not added by user, it gets added automatically.

> I appreciate the PR suggestion, although, I'd like to get rid of that lazy stuff I put there, whereby I don't validate that the given stuff is indeed a macro path (that is, since we don't use syn, we'd need to parse an alternate sequence of Punct(':', Spacing::Joint), Punct(':', Spacing::Alone), Ident (with an optional leading ::));

I can work on that too! Shouldn't be too hard.
